language: node_js

sudo: false

node_js: 
  - "7.10.0"

before_install:
  - export TZ='Asia/Shanghai'

cache:
  apt: true
  directories:
    - node_modules

addons:
  ssh_known_hosts: 
    - git.coding.net
    - git.oschina.net

script:
  - hexo clean 
  - hexo generate

deploy:
  provider: script
  script: sh .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master

dist: precise

branches:
  only:
    - master
