language: node_js

sudo: false

node_js: 
  - "7.10.0"

cache:
  apt: true
  directories:
    - node_modules

addons:
  ssh_known_hosts: 
    - git.coding.net
    - git.oschina.net

script:
  - hexo clean 
  - hexo generate

dist: trusty

branches:
  only:
    - master
